### ISSUE TITLE
Not working (Ubuntu ARM64)

### ISSUE THREAD

**Issue by unvency** [zac-bostick/PrivateYoutubeSync#1]
Hey there! I hope you can help here :)

```
root@instance-20230910-0110:/mnt/PYTS# sudo npm start

> testserver@1.0.0 start /mnt/PYTS
> node server.js

/mnt/PYTS/server.js:25
      const thumbnailUrl = video.snippet.thumbnails?.maxres?.url || video.snippet.thumbnails?.high?.url || video.snippet.thumbnails?.default?.url;
                                                    ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testserver@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testserver@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-09-10T02_35_39_790Z-debug.log

```

Log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle testserver@1.0.0~prestart: testserver@1.0.0
6 info lifecycle testserver@1.0.0~start: testserver@1.0.0
7 verbose lifecycle testserver@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle testserver@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/PYTS/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle testserver@1.0.0~start: CWD: /mnt/PYTS
10 silly lifecycle testserver@1.0.0~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle testserver@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle testserver@1.0.0~start: Failed to exec start script
13 verbose stack Error: testserver@1.0.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid testserver@1.0.0
15 verbose cwd /mnt/PYTS
16 verbose Linux 5.15.0-1042-oracle
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error testserver@1.0.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the testserver@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

OAuth Credentials were entered correctly

**Comment by zacbostick** [comment]
Hi there @unvency !

Thank you for trying out my code and bringing this to my attention!

The error you're encountering is related to the use of "optional chaining" (`?.`) in JavaScript, which is a newer feature introduced in ECMAScript 2020 (ES11). The version of Node.js you're using (v10.19.0) doesn't support this feature, hence the error.

To resolve this issue, you have a couple of options:

1. Upgrade Node.js: I recommend upgrading to Node.js version v14.x or newer. This will not only resolve this specific issue but will also ensure you're running a more secure and updated version of Node.js, which supports the latest JavaScript features.

2. Refactor the Code: If you prefer not to upgrade Node.js, you can refactor the part of the code using optional chaining to avoid this feature. For instance, something like this: 

`let thumbnailUrl;
if (video.snippet.thumbnails && video.snippet.thumbnails.maxres && video.snippet.thumbnails.maxres.url) {
    thumbnailUrl = video.snippet.thumbnails.maxres.url;
} else if (video.snippet.thumbnails && video.snippet.thumbnails.high && video.snippet.thumbnails.high.url) {
    thumbnailUrl = video.snippet.thumbnails.high.url;
} else if (video.snippet.thumbnails && video.snippet.thumbnails.default && video.snippet.thumbnails.default.url) {
    thumbnailUrl = video.snippet.thumbnails.default.url;
}
`

should work in place of this:

`const thumbnailUrl = video.snippet.thumbnails?.maxres?.url || video.snippet.thumbnails?.high?.url || video.snippet.thumbnails?.default?.url;`

Let me know if this helps at all!
